# oop's(continution.....)

### Class
- Collection of variables and Methods
- Function : Collection of Statements
- Method : Function is inside the class then it is called method
- class is keyword for creating  class structure.
##### Syntax: 
class class_name:
     vars
     methods

### Object
- Instance of Class
#### Syntax:
object_name = class_name()
- object is created many times as per requirement
- class is declared once.

### Constructor
-  which is used to initialize the instance members of the class.
- in python for creating constructor we will use __init__(self)
- in constructor self parameter finds the current reference object.
- Advantage of constructor is without using object we wil call function.
- create object for class but does not use that object to call the function.
#### syn:
class class_name:
    def __init__(self): # it is constructor  # default parameter is self
    def __init__(self,a,b) #fisrt variable acts as default parameter
    def __init__(a,b,self)  # here a acts as default parameter     

In [11]:
class math:
    def __init__(self,a,b):
        self.a=a
        self.b=b
        print(a,b)
        print("hello")

In [12]:
o=math(2,3)

2 3
hello


### Inheritance
- it specifies that the child object acquires all the properties and behaviors of the parent object.
- By using inheritance,we can create a class which uses all the properties and behavior of another 
  class. 
- The new class is known as a derived class or child class, 
- and the one whose properties are acquired is known as a base class or parent class.
- It provides re-usability of the code.
- we are trying to inheriting something from parent class to child class
#### syntax:
class childclass(parentclass):
- Single level inheritence --one parent,one child
- multilevel -- One or more parents or one or more child.
  (there is no fixed numbers of parents and childs)
- multiple -- multiple/morethan one parents and single child.
- Hierarchical--(single parent multiple childs)
- hybrid -- multiple parents and multiple child // Combination of all inhritance.

In [13]:
# single level inhertance:(one parent,one child)
class ClassA():
    a,b=10,30
    def display():
        print("iam from class A")
class ClassB(ClassA):
    c,d=23,56
    def show():
        print("iam from class B")

In [21]:
obj=ClassA
print(obj.a)
print(obj.b)
obj.display()
print(obj.c)
print(obj.d)
obj.show()

10
30
iam from class A


AttributeError: type object 'ClassA' has no attribute 'c'

In [20]:
obj=ClassB
print(obj.a)
print(obj.b)
obj.display()
print(obj.c)
print(obj.d)
obj.show()

10
30
iam from class A
23
56
iam from class B


In [29]:
# multilevel(one parent,1 childa to 1 childb)
class ClassA():
    def Classa():
        print("iam from class A")
class ClassB(ClassA):
    def Classb():
        print("iam from class B")
class ClassC(ClassB):
    def Classc():
        print("iam from class B")

In [30]:
ob=ClassC
ob.Classa()
ob.Classb()
ob.Classc()

iam from class A
iam from class B
iam from class B


In [31]:
# multiple(more parents,one child)
class ClassA():
    def Classa():
        print("iam from class A")
class ClassB():
    def Classb():
        print("iam from class B")
class ClassC(ClassA,ClassB):
    def Classc():
        print("iam from class B")

In [36]:
ob1=ClassC
ob1.Classa()
ob1.Classb()
ob1.Classc()

iam from class A
iam from class B
iam from class B


In [ ]:
#task
# single parent,multiple childs(heirarchical)
a(parent)
b,c(childs)
#hybrid(multiple,multilevel)
a,b
c(grand father)
d(father)
e(grandchild)

In [ ]:
# pacakges and modules using oops
#modules:(.py file)
- group of functions and classes
#packages(folder)
- collection of modules

In [1]:
from packages.programs import *
obj=calsi
print(obj.add(2,5))
print(obj.mul(2,6))
print(obj.sub(2,3))
print(obj.div(2,5))
print(obj.mod(5,6))

7
12
-1
0.4
5


In [6]:
from packages.programs import math
obj1=math
print(obj1.power(2,5))
print(obj1.IsEven(6))
print(obj1.IsOdd(6))
print(obj1.IsOdd(int(input())))

32
True
False
7
True


In [2]:
from packages.programs import *
obj2=cal(5,7)
print(obj2.__add__())
print(obj2.__mul__())

12
35


In [ ]:
# Python Libraries for datascience
# datascience:
- organising,processing,analysing the huge amount of data.
- apply data visualization
- extracting the data from the source.
- nearly 20 python libraries for datascience
#top 3
- numpy
- pandas
- matplotlib

In [ ]:
# Numpy(numerical python)
- it is a fundamental package for scientific computing in python.
- numpy is a python library
- it is used to creat multidimensional arrays for fast operations.
- for installing numpy---->pip install numpy
- use the following import conversion to access numpy library
    - import numpy as np

In [4]:
# 1 dimensional array
import numpy as np
array1d=np.array([2,3,4,5,5])
print(array1d)
print(type(array1d))

[2 3 4 5 5]
<class 'numpy.ndarray'>


In [5]:
# 2 dimensional array
import numpy as np
array2d=np.array([[2,3,4],[5,6,9]])
print(array2d)
print(type(array2d))

[[2 3 4]
 [5 6 9]]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
array2d=np.array([[2,3,4,8,9],[5,6,9]])
print(array2d)
print(type(array2d))
array2d

[list([2, 3, 4, 8, 9]) list([5, 6, 9])]
<class 'numpy.ndarray'>


array([list([2, 3, 4, 8, 9]), list([5, 6, 9])], dtype=object)

In [9]:
#list into array using numpy
import numpy as np
li=[2,3,4,'f','l']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))
a1

<class 'list'>
['2' '3' '4' 'f' 'l']
<class 'numpy.ndarray'>


array(['2', '3', '4', 'f', 'l'], dtype='<U11')

In [11]:
# using arange() function
import numpy as np
a=np.arange(15)
print(a)
print(type(a))
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
# using reshape(row,columns)
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(type(a))
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
import numpy as np
a=np.arange(15).reshape(4,10)
print(a)
print(type(a))
a

ValueError: cannot reshape array of size 15 into shape (4,10)

In [17]:
#if the array size is too large,then numpy will skips the middle numbers with ...
import numpy as np
a=np.arange(10000)
print(a)
print(type(a))
a

[   0    1    2 ... 9997 9998 9999]
<class 'numpy.ndarray'>


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [18]:
import numpy as np
a=np.arange(10000).reshape(100,100)
print(a)
print(type(a))
a

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
<class 'numpy.ndarray'>


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [19]:
import numpy as np
a=np.arange(10000).reshape(50,200)
print(a)
print(type(a))
a

[[   0    1    2 ...  197  198  199]
 [ 200  201  202 ...  397  398  399]
 [ 400  401  402 ...  597  598  599]
 ...
 [9400 9401 9402 ... 9597 9598 9599]
 [9600 9601 9602 ... 9797 9798 9799]
 [9800 9801 9802 ... 9997 9998 9999]]
<class 'numpy.ndarray'>


array([[   0,    1,    2, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  397,  398,  399],
       [ 400,  401,  402, ...,  597,  598,  599],
       ...,
       [9400, 9401, 9402, ..., 9597, 9598, 9599],
       [9600, 9601, 9602, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9997, 9998, 9999]])

In [20]:
import numpy as np
a=np.arange(10000).reshape(10000,1)
print(a)
print(type(a))
a

[[   0]
 [   1]
 [   2]
 ...
 [9997]
 [9998]
 [9999]]
<class 'numpy.ndarray'>


array([[   0],
       [   1],
       [   2],
       ...,
       [9997],
       [9998],
       [9999]])

In [ ]:
#ndarray (tommorrow continution)

In [22]:
print(dir(np),end=" ")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste