In [ ]:
# Pandas (Continution....)
- Series
- DataFrames

In [ ]:
# Panda Series:

In [1]:
import pandas as pd
pd.__version__

'0.24.2'

In [2]:
s="hello"
pd.Series(s)

0    hello
dtype: object

In [3]:
s1=input().split()
pd.Series(s1)

pavani ambika surya


0    pavani
1    ambika
2     surya
dtype: object

In [4]:
l=[23,'abc',89.78]
pd.Series(l)

0       23
1      abc
2    89.78
dtype: object

In [5]:
t=(23,24,25,67,89)
pd.Series(t)

0    23
1    24
2    25
3    67
4    89
dtype: int64

In [6]:
s={23,2,3,23,45,67,23}
pd.Series(s)

TypeError: 'set' type is unordered

In [7]:
d={'course':'python','org':'apssdc','training':'online'}
pd.Series(d)

course      python
org         apssdc
training    online
dtype: object

In [9]:
import pandas as pd
import numpy as np
a=np.arange(4,10)
pd.Series(a)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int32

In [14]:
r=np.random.randint(2,20,10)
pd.Series(r)

0     4
1    15
2     7
3     5
4    15
5    18
6    17
7    16
8    16
9     3
dtype: int32

In [19]:
print(r[5])
print(r[::-1])
print(r[:4])
print(r[::2])

18
[ 3 16 16 17 18 15  5  7 15  4]
[ 4 15  7  5]
[ 4  7 15 17 16]


In [25]:
n=int(input("enter a num:"))
l={i:i**2 for i in range(1,n+1)}
pd.Series(l)

enter a num:5


1     1
2     4
3     9
4    16
5    25
dtype: int64

In [23]:
a=pd.Series(np.arange(0,15)**2,index=range(0,15))
print(a)

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
11    121
12    144
13    169
14    196
dtype: int32


In [ ]:
# Data Frames:
- (default table format)
- 2d labeled array
- there are mostly used in dataanalysis.

In [28]:
import pandas as pd
n=input().split()
pd.DataFrame(n)

python workshop


0
0    python
1  workshop

In [29]:
d=[['ambika','ece'],['pavani','cse'],['surya','cse']]
pd.DataFrame(d)

0    1
0  ambika  ece
1  pavani  cse
2   surya  cse

In [30]:
d=[['ambika','ece'],['pavani','cse'],['surya','cse']]
pd.DataFrame(d,columns=['Name','Branch'])

Name Branch
0  ambika    ece
1  pavani    cse
2   surya    cse

In [31]:
d=[['ambika','ece'],['pavani','cse'],['surya','cse']]
pd.DataFrame(d,index=['one','two','three'],columns=['Name','Branch'])

Name Branch
one    ambika    ece
two    pavani    cse
three   surya    cse

In [35]:
d=[[1,2,3],[4,5,6]]
pd.DataFrame(d,columns=['1st','2nd','3rd'])

1st  2nd  3rd
0    1    2    3
1    4    5    6

In [47]:
d1={'Name':'Pavani','Org':'Apssdc','Training':'Python'}
pd.DataFrame(d1,index=[1])

Name     Org Training
1  Pavani  Apssdc   Python

In [48]:
d2={'collge':'Aditya','Branch':'Cse','hello':'everyone'}
pd.DataFrame(d1,d2)

Name     Org Training
collge  Pavani  Apssdc   Python
Branch  Pavani  Apssdc   Python
hello   Pavani  Apssdc   Python

In [49]:
d3={'python':'workshop','Online':'Workshop','30-7-2020':'day-16'}
pd.DataFrame(d1,d2,d3)

python Online 30-7-2020
collge    NaN    NaN       NaN
Branch    NaN    NaN       NaN
hello     NaN    NaN       NaN

In [57]:
a={'python':22,'c':18,'java':20}
b=pd.Series(a)

c={'python':23,'java':23}
d=pd.Series(c)
print(b,'\n''\n',d)

python    22
c         18
java      20
dtype: int64 

 python    23
java      23
dtype: int64


In [58]:
final={'mid1':b,'mid2':d}
pd.DataFrame(final)

mid1  mid2
c         18   NaN
java      20  23.0
python    22  23.0

In [54]:
a={'python':22,'c':18,'java':20}
b=pd.Series(a)

c={'python1':24,'c1':20,'java1':23}
d=pd.Series(c)
print(b,'\n''\n',d)

python    22
c         18
java      20
dtype: int64 

 python1    24
c1         20
java1      23
dtype: int64


In [55]:
final={'mid1':b,'mid2':d}
pd.DataFrame(final)

mid1  mid2
c        18.0   NaN
c1        NaN  20.0
java     20.0   NaN
java1     NaN  23.0
python   22.0   NaN
python1   NaN  24.0

In [60]:
d=pd.DataFrame({'name':['pavani','ambika'],'age':[23,24],'Branch':['cse','ece']})
print(d)

     name  age Branch
0  pavani   23    cse
1  ambika   24    ece


In [81]:
import pandas as pd
t1={'Name':'pavani','Orgi':'apssdc','Training':'online'}
t2={'Name':'ambika','Orgi':'apssdc'}
t3={'Name':'surya','Orgi':'apssdc','Training':'online','Branch':'cse'}
a=pd.DataFrame([t1,t2,t3],index=['Name','Orgi','Training'])
b=pd.DataFrame([t1,t2,t3],columns=['Name','Orgi'])
c=pd.DataFrame([t1,t2,t3],columns=['Name','Orgi','Training','Branch'])
a

Branch    Name    Orgi Training
Name        NaN  pavani  apssdc   online
Orgi        NaN  ambika  apssdc      NaN
Training    cse   surya  apssdc   online

In [82]:
b

Name    Orgi
0  pavani  apssdc
1  ambika  apssdc
2   surya  apssdc

In [83]:
c

Name    Orgi Training Branch
0  pavani  apssdc   online    NaN
1  ambika  apssdc      NaN    NaN
2   surya  apssdc   online    cse

In [84]:
a

Branch    Name    Orgi Training
Name        NaN  pavani  apssdc   online
Orgi        NaN  ambika  apssdc      NaN
Training    cse   surya  apssdc   online

In [87]:
a.loc['Name']

Branch         NaN
Name        pavani
Orgi        apssdc
Training    online
Name: Name, dtype: object

In [92]:
a.iloc[1]

Branch         NaN
Name        ambika
Orgi        apssdc
Training       NaN
Name: Orgi, dtype: object

In [93]:
a['Branch']='CSE'
a

Branch    Name    Orgi Training
Name        CSE  pavani  apssdc   online
Orgi        CSE  ambika  apssdc      NaN
Training    CSE   surya  apssdc   online

In [94]:
a.T

Name    Orgi Training
Branch       CSE     CSE      CSE
Name      pavani  ambika    surya
Orgi      apssdc  apssdc   apssdc
Training  online     NaN   online

In [95]:
a.T.loc['Orgi']

Name        apssdc
Orgi        apssdc
Training    apssdc
Name: Orgi, dtype: object

In [96]:
a.T.iloc[3]

Name        online
Orgi           NaN
Training    online
Name: Training, dtype: object

In [102]:
d1=pd.DataFrame({'num':[2,1,3,4],'age':[50,45,60,79]},index=[2002,2003,2004,2005])
d1

num  age
2002    2   50
2003    1   45
2004    3   60
2005    4   79

In [105]:
d2=pd.DataFrame({'num1':[80,30,40,50],'age1':[1,2,3,1]},index=[2011,2002,2020,2003])
d2

num1  age1
2011    80     1
2002    30     2
2020    40     3
2003    50     1

In [106]:
d1.join(d2)

num  age  num1  age1
2002    2   50  30.0   2.0
2003    1   45  50.0   1.0
2004    3   60   NaN   NaN
2005    4   79   NaN   NaN

In [107]:
d2.join(d1)

num1  age1  num   age
2011    80     1  NaN   NaN
2002    30     2  2.0  50.0
2020    40     3  NaN   NaN
2003    50     1  1.0  45.0

In [115]:
d3=pd.DataFrame({'weight':[50,60,70,80],'age':[45,6,89,90]},index=[2002,2003,2004,2005])
d4=pd.DataFrame({'weight':[50,60,70,80],'age':[45,6,89,90],'branch':['cse','cse','ece','cse']},index=[2010,2003,2013,2004])
d3

weight  age
2002      50   45
2003      60    6
2004      70   89
2005      80   90

In [116]:
d4

weight  age branch
2010      50   45    cse
2003      60    6    cse
2013      70   89    ece
2004      80   90    cse

In [117]:
d3.merge(d4)

weight  age branch
0      50   45    cse
1      60    6    cse
2      70   89    ece
3      80   90    cse

In [118]:
d3.merge(d4,on='weight')

weight  age_x  age_y branch
0      50     45     45    cse
1      60      6      6    cse
2      70     89     89    ece
3      80     90     90    cse

In [120]:
c=pd.concat([d3,d4])
c

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


age branch  weight
2002   45    NaN      50
2003    6    NaN      60
2004   89    NaN      70
2005   90    NaN      80
2010   45    cse      50
2003    6    cse      60
2013   89    ece      70
2004   90    cse      80

In [121]:
d=pd.date_range('2020-11-12',periods=5)
d

DatetimeIndex(['2020-11-12', '2020-11-13', '2020-11-14', '2020-11-15',
               '2020-11-16'],
              dtype='datetime64[ns]', freq='D')

In [124]:
d1=pd.date_range('2020-01-11','2020-01-20')
pd.Series(d1)

0   2020-01-11
1   2020-01-12
2   2020-01-13
3   2020-01-14
4   2020-01-15
5   2020-01-16
6   2020-01-17
7   2020-01-18
8   2020-01-19
9   2020-01-20
dtype: datetime64[ns]