- Packages and Modules using OOPS
    - similar to packages and modules using functions
    - But here we are dealing with classes and objects

In [1]:
from Packages.myModule import *
obj = Calci
obj.add(10,10)

20

In [3]:
from Packages.myModule import *
obj1 = Calci1
obj1.power(2,3)
obj1.isEven(6)

True

In [4]:
from Packages.myModule import *
obj2 = Modu(2,5)
print(obj2.__add__())
print(obj2.__mul__())
#print(type(obj2.__add__()))

7
10
<class 'int'>


- Data Science
    - Organising,processing and analysing huge amount of data.
    - It involves different disciplines like mathematical and statistical modelling
    - extrecating data from source
    - Apply data visulaization
    - Nearly 20 python libraries for data science

- Numpy
    - Numerical Python
    - Fundamental package for scientific computing
    - multidimensional array object
- Installation
    - pip install numpy
    - sudo apt-get install python3 numpy

In [2]:
import numpy as np
np.__version__

'1.15.4'

In [6]:
np?

In [3]:
# creating array using numpy
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1.0,2,3,4,5])

array([1., 2., 3., 4., 5.])

In [5]:
np.array([1.0,2,3,4,5],dtype='int')

array([1, 2, 3, 4, 5])

In [6]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
x = np.arange(10).reshape((2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
data = np.random.randint(1,50)
data

22

In [12]:
data = np.random.randint(1,10,size=(5,5))
data

array([[4, 1, 2, 3, 1],
       [5, 6, 3, 4, 1],
       [5, 2, 5, 6, 9],
       [8, 7, 8, 3, 9],
       [9, 3, 6, 3, 1]])

In [25]:
import numpy as np
data = np.random.randint(1,10,size=(5,5))
print(data)
# returns the number of dimensions
print(data.ndim)
# shape of matrix
print(data.shape)
# size of matrix
print(data.size)
# datatype of matrix
print(data.dtype)
# returns the size of element in bytes format
print(data.itemsize)

[[6 2 5 7 6]
 [8 7 6 2 7]
 [4 9 3 2 6]
 [2 4 3 7 9]
 [3 1 2 7 1]]
2
(5, 5)
25
int32
4


In [13]:
data

array([[4, 1, 2, 3, 1],
       [5, 6, 3, 4, 1],
       [5, 2, 5, 6, 9],
       [8, 7, 8, 3, 9],
       [9, 3, 6, 3, 1]])

In [14]:
data[::-1]

array([[9, 3, 6, 3, 1],
       [8, 7, 8, 3, 9],
       [5, 2, 5, 6, 9],
       [5, 6, 3, 4, 1],
       [4, 1, 2, 3, 1]])

In [15]:
# create a length-10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [17]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full((2,3),1.14)

array([[1.14, 1.14, 1.14],
       [1.14, 1.14, 1.14]])

In [20]:
# evenly spaced elements in array using linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Identity matrix
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
x = np.array([-2,-2,1,0,2,3])
abs(x)

array([2, 2, 1, 0, 2, 3])

In [24]:
np.absolute(x)

array([2, 2, 1, 0, 2, 3])

In [25]:
# trignometric operations
t = np.linspace(0,np.pi,3)
t

array([0.        , 1.57079633, 3.14159265])

In [27]:
print("sin(t) = ",np.sin(t))
print("cos(t) = ",np.cos(t))
print("tan(t) = ",np.tan(t))

sin(t) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(t) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(t) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [28]:
x = [1,2,3]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


In [31]:
a = np.arange(3)
print(a)
print(a.shape)

[0 1 2]
(3,)


In [32]:
b = np.arange(3)[:,np.newaxis]
print(b)
print(b.shape)

[[0]
 [1]
 [2]]
(3, 1)


In [33]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [34]:
a - b

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [35]:
a * b

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [36]:
a / b

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf],
       [0. , 1. , 2. ],
       [0. , 0.5, 1. ]])

In [37]:
b / a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [38]:
# comparision operators
a

array([0, 1, 2])

In [39]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [40]:
x < 3 

array([ True,  True, False, False, False])

In [41]:
x > 3

array([False, False, False,  True,  True])

In [42]:
x >= 3

array([False, False,  True,  True,  True])

In [43]:
x <= 3

array([ True,  True,  True, False, False])

In [44]:
x == 3

array([False, False,  True, False, False])

In [45]:
x != 3

array([ True,  True, False,  True,  True])

In [46]:
# returns how many values less than 3
np.count_nonzero(x<3)

2

In [47]:
np.sum(x<3)

2

In [49]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
np.sum(y<3,axis=1)

array([2, 0, 0])

In [53]:
y.sort()
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
x = np.array([2,7,9,4,1])
print(x)

[2 7 9 4 1]


In [55]:
np.sort(x)

array([1, 2, 4, 7, 9])

In [56]:
x.sort()
print(x)

[1 2 4 7 9]


In [57]:
#argsort() returns the index position of elements
x = np.array([2,7,9,4,1])
i = np.argsort(x)
print(i)

[4 0 3 1 2]


In [64]:
import random
y = np.random.randint(0,10,(4,6))
h = np.argsort(y)
print(h)

[[3 5 0 1 2 4]
 [3 4 5 0 1 2]
 [0 2 3 1 4 5]
 [2 1 3 4 5 0]]


In [60]:
import random
x = np.random.randint(0,10,(4,6))
x

array([[3, 3, 4, 6, 5, 6],
       [9, 0, 4, 5, 2, 6],
       [8, 3, 3, 0, 4, 6],
       [5, 4, 2, 8, 8, 3]])

In [61]:
# column sort
np.sort(x,axis=0)

array([[3, 0, 2, 0, 2, 3],
       [5, 3, 3, 5, 4, 6],
       [8, 3, 4, 6, 5, 6],
       [9, 4, 4, 8, 8, 6]])

In [62]:
# row sort
np.sort(x,axis=1)

array([[3, 3, 4, 5, 6, 6],
       [0, 2, 4, 5, 6, 9],
       [0, 3, 3, 4, 6, 8],
       [2, 3, 4, 5, 8, 8]])