# Numpy (Continution....)

In [1]:
import numpy as np
np.__version__

'1.16.4'

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1.23,2,3,4,5])

array([1.23, 2.  , 3.  , 4.  , 5.  ])

In [6]:
np.array([1,2,3,4,5],dtype='int')

array([1, 2, 3, 4, 5])

In [7]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3,5),56.78)

array([[56.78, 56.78, 56.78, 56.78, 56.78],
       [56.78, 56.78, 56.78, 56.78, 56.78],
       [56.78, 56.78, 56.78, 56.78, 56.78]])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [14]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [19]:
np.random.randint(1,50,size=(4,4))

array([[25,  7, 30,  8],
       [34, 14, 10, 40],
       [32, 16, 38, 14],
       [16,  9, 26, 41]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
d=np.array([2,3,4,6])
np.diag(d)

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [22]:
d=np.array([2,3,4,6]*3)
d

array([2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6])

In [23]:
d=np.repeat([2,3,4,6],3)
d

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 6, 6, 6])

In [24]:
a=np.array([0,1,2])
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [25]:
a*3

array([0, 3, 6])

In [ ]:
# nd array--->
1)ndarray.ndim
2)ndarray.shape
3)ndarray.dtype
4)ndarray.size
5)ndarray.itemsize

In [31]:
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize) # returns the size in bytes

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6
int32
4


In [32]:
a[::-1]

array([[2, 3, 4],
       [1, 2, 3]])

In [35]:
n1=np.arange(1,5).reshape(2,2)
n2=np.arange(5,9).reshape(2,2)
print(n1)
print(n2)
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1%n2)
print(n1//n2)
print(n1**n2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]
[[    1    64]
 [ 2187 65536]]


In [37]:
print(n1)
print(n2)
print(n1.dot(n2)) # matrix multiplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [38]:
x=np.array([2,4,1,5,3])
np.sort(x)

array([1, 2, 3, 4, 5])

In [41]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[[1 2 3]
 [4 5 6]]
6
1
21
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [44]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.max(axis=0))   #max row
print(a.max(axis=1))   # max column

[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 6]


In [46]:
a=np.array([2,3,4,5,1])
print(a[0])
print(a[3])

2
5


In [47]:
a<3

array([ True, False, False, False,  True])

In [56]:
a=np.array([[10,2,30],[22,5,8]])
print(a)
print(np.sort(a,axis=0))  #columns
print(np.sort(a,axis=1))  #rows

[[10  2 30]
 [22  5  8]]
[[10  2  8]
 [22  5 30]]
[[ 2 10 30]
 [ 5  8 22]]


In [61]:
print(a[0])
print(a[1])

[10  2 30]
[22  5  8]


In [82]:
b=np.arange(3)
a=np.arange(4)[:,np.newaxis]
c=a+b
print(b)
print(a)
print(a[0])

[0 1 2]
[[0]
 [1]
 [2]
 [3]]
[0]


In [83]:
print(c)
print(c[2][2])
print(c[0])

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]
4
[0 1 2]


In [84]:
print(c[:,1])

[1 2 3 4]


In [92]:
n=np.ones((3,3),dtype="int")
print(n)
np.vstack((n,np.array((2,2,2))))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
# vstack
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]    + [[2.,2.,2.]]

In [ ]:
#hstack
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]    + [[2.
                    2.
                    2.]] 

In [87]:
n=np.ones((3,3))
b=np.array((2,2,2)).reshape(3,1)
print(n)
print(b)
np.hstack((n,b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2]
 [2]
 [2]]


array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [ ]:
# pandas:
- it is  an open source python library that produces high performance
- load,prepare,manipulate,model,analyze
- panadas basically use for data analysis.
- data cleaning
- data transformation
- data analysis
# panads notations
1) panada Series
2) Panada DataFrames

In [ ]:
#datastructures in python pandas:
1)Series(similar to numpy array)
- creating a panadas series
- indexing series
2)Data Frame(default table format)
- creating dataframes from dictionaries
- importing csv data files as panda dataframes
- reading and summarising dataframes
- sorting dataframes

In [ ]:
- pip install pandas

In [ ]:
#1) Panda Series
- series is a 1d labeled array holds any data type like int,float,string.
- it is collectively called as index.
#syn:
- pd.Series(data,index,dtype)

In [93]:
import pandas as pd
a=pd.Series([1,2,3,4,5])
print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [95]:
import pandas as pd
b=pd.Series(['pavani','ambika','surya'])
print(b)
print(type(b))

0    pavani
1    ambika
2     surya
dtype: object
<class 'pandas.core.series.Series'>


In [97]:
import pandas as pd
c=pd.Series(['pavani','ambika','surya',1,2,3,5.78])
print(c)
print(type(c))

0    pavani
1    ambika
2     surya
3         1
4         2
5         3
6      5.78
dtype: object
<class 'pandas.core.series.Series'>


In [104]:
print(c[0])
print(c[5])
#print(c[-1])
print(c[1:5])

pavani
3
1    ambika
2     surya
3         1
4         2
dtype: object


In [105]:
print(c[::-1])

6      5.78
5         3
4         2
3         1
2     surya
1    ambika
0    pavani
dtype: object


In [107]:
print(c[-5:-1])

2    surya
3        1
4        2
5        3
dtype: object


In [109]:
c

0    pavani
1    ambika
2     surya
3         1
4         2
5         3
6      5.78
dtype: object

In [113]:
import pandas as pd
a=pd.Series([1,2,3],index=['a','b','c'])
print(a)

a    1
b    2
c    3
dtype: int64


In [114]:
import pandas as pd
a=pd.Series([1,2,3],index=['a','b','c','d','e'])
print(a)

ValueError: Length of passed values is 3, index implies 5

In [117]:
import pandas as pd
a=pd.Series([1,2,3],index=pd.date_range('22-11-2020','24-11-2020'))
print(a)

2020-11-22    1
2020-11-23    2
2020-11-24    3
Freq: D, dtype: int64


In [120]:
import pandas as pd
a=pd.Series([1,2,3],index=('2-4-2020','3-4-2020','4-4-2020'))
print(a)

2-4-2020    1
3-4-2020    2
4-4-2020    3
dtype: int64


In [119]:
import pandas as pd
a=pd.Series([1,2,3],index=pd.date_range('2-4-2020','4-4-2020'))
print(a)

ValueError: Length of passed values is 3, index implies 61