In [1]:
import numpy as np
np.__version__

'1.15.4'

In [2]:
print(dir(np),end=" ")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

In [4]:
# Vstack and hstack
a = np.ones((3,3))
np.vstack((a,np.array((2,2,2))))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [5]:
a = np.ones((3,3))
np.hstack((a,np.array((2,2,2))))

ValueError: all the input arrays must have same number of dimensions

In [ ]:
# [[1,1,1
1,1,1
1,1,1,]]   + [2,2,2]

In [6]:
a = np.ones((3,3))
b = np.array((2,2,2)).reshape(3,1)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2]
 [2]
 [2]]


In [8]:
np.hstack((a,b))

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [9]:
name = ['Ambika','pavani','surya','keerthi']
age = [25,27,29,22]
weight = [40.0,45.5,55.5,42.0]

In [17]:
x = np.zeros(4,dtype=int)
x

array([0, 0, 0, 0])

In [10]:
# create structured array using compound data types
data = np.zeros(4,dtype={'names':('name','age','weight'),
                        'formats':('U10','i4','f8')})
print(data.dtype)                  

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


- U10 -- Unicode string
- i4 - translate to 4 bytes integer
- f8 - translate to 8 byte float

In [11]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Ambika', 25, 40. ) ('pavani', 27, 45.5) ('surya', 29, 55.5)
 ('keerthi', 22, 42. )]


In [12]:
data['name']

array(['Ambika', 'pavani', 'surya', 'keerthi'], dtype='<U10')

In [13]:
data[0]

('Ambika', 25, 40.)

In [14]:
data[-1]

('keerthi', 22, 42.)

In [15]:
data[data['age']<29]['name']

array(['Ambika', 'pavani', 'keerthi'], dtype='<U10')

- Pandas
    - One of data science package
    - data manupulation tool,data analysing and data cleaning
    - built on numpy
    - devloped by WesMCkinney
- Installation
    - Windows
        - pip install pandas
    - linux
        - sudo apt-get install python3 pandas
- Key structures
    - Series
        - sequence of data
        - one dimensional array  used to store data of any type(int,float,string,python objects)
        - syntax
            - pd.Series(var,index=[])
    - dataFrames
        - two dimensional array
        - data with rows and columns
        - syntax
            - pd.DataFrame(var,index,columns)

In [18]:
import pandas as pd
pd.__version__

'0.23.4'

In [19]:
st = 'hello'
pd.Series(st)

0    hello
dtype: object

In [20]:
st1 = input().split()
pd.Series(st1)

python program


0     python
1    program
dtype: object

In [21]:
li = [1,2,3,4,5]
pd.Series(li)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:
li1 = ['abc',1,2,3,7.9]
pd.Series(li1,index=['A','B','C','D','E'])

A    abc
B      1
C      2
D      3
E    7.9
dtype: object

In [25]:
d = {'Course':'python','Org':'APSSDC','Branches':'All'}
pd.Series(d)

Course      python
Org         APSSDC
Branches       All
dtype: object

In [28]:
pd.Series(d,index=['A','B','C'])
# None 
#Not A Number

A    NaN
B    NaN
C    NaN
dtype: object

In [29]:
pd.Series(d,index=['A','Org','Branches'])

A              NaN
Org         APSSDC
Branches       All
dtype: object

In [31]:
import numpy as np
ar = np.arange(4,10)
#print(ar)
pd.Series(ar)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int32

In [34]:
r = np.random.randint(2,20,8)
s = pd.Series(r)
s

0    11
1    11
2     5
3    10
4     5
5    13
6    18
7     7
dtype: int32

In [35]:
s[0:5]

0    11
1    11
2     5
3    10
4     5
dtype: int32

In [36]:
s[0:]

0    11
1    11
2     5
3    10
4     5
5    13
6    18
7     7
dtype: int32

In [37]:
s[:5]

0    11
1    11
2     5
3    10
4     5
dtype: int32

In [38]:
s[0:5:2]

0    11
2     5
4     5
dtype: int32

8 
index  values
1        1
2        4
3        9

In [39]:
# without numpy
num = int(input("Enter number: "))
l = {i:i**2 for i in range(1,num)}
o = pd.Series(l)
o

Enter number: 10


1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [40]:
out = pd.Series(np.array(range(1,10))**2,index=range(1,10))
out

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [41]:
name = input("Enter string: ").split()
pd.DataFrame(name)

Enter string: python program


0
0   python
1  program

In [42]:
l = [1,2,3,4]
pd.DataFrame(l)

0
0  1
1  2
2  3
3  4

In [44]:
lone = [[1,2,3],[4,5,6]]
pd.DataFrame(lone)

0  1  2
0  1  2  3
1  4  5  6

In [45]:
data = [['Ambika','Python'],['Pavani','Gaming'],['Surya','Cyber']]
pd.DataFrame(data)

0       1
0  Ambika  Python
1  Pavani  Gaming
2   Surya   Cyber

In [47]:
pd.DataFrame(data,index=['One','Two','Three'])

0       1
One    Ambika  Python
Two    Pavani  Gaming
Three   Surya   Cyber

In [48]:
pd.DataFrame(data,index=['One','Two','Three'],columns=['Name','Field'])

Name   Field
One    Ambika  Python
Two    Pavani  Gaming
Three   Surya   Cyber

In [49]:
d = {'Name':'Ambika','Org':'APSSDC','Team':'Python'}
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [50]:
pd.DataFrame(d,index=[1])

Name     Org    Team
1  Ambika  APSSDC  Python

In [51]:
pd.DataFrame(d,index=[1],columns=['Name','Org','Field'])

Name     Org Field
1  Ambika  APSSDC   NaN

In [52]:
dic1 = {'Name':'Ambika','Org':'APSSDC','Team':'Python'}
dic2 = {'Clg':'Svecw','Branch':'ECE'}
pd.DataFrame(dic1,dic2)

Name     Org    Team
Clg     Ambika  APSSDC  Python
Branch  Ambika  APSSDC  Python

In [54]:
pd.DataFrame([dic1,dic2],index=['Two','One'])

Branch    Clg    Name     Org    Team
Two    NaN    NaN  Ambika  APSSDC  Python
One    ECE  Svecw     NaN     NaN     NaN

In [55]:
pd.DataFrame([dic1,dic2],index=['One','Two'],columns=['Name','clg','Branch','org','team'])

Name  clg Branch  org  team
One  Ambika  NaN    NaN  NaN   NaN
Two     NaN  NaN    ECE  NaN   NaN

In [57]:
dic1 = {'Name':'Ambika','Org':'APSSDC','Team':'Python'}
dic2 = {'Name':'Pavani','Org':'APSSDC','Field':'Gaming'}
dic3 = {'Name':'Surya','Org':'APSSDC','Team':'Cyber','Exp':'4'}
dic4 = {'Name':'Keerthi','Org':'APSSDC','Team':'MSTP'}
s = pd.DataFrame([dic1,dic2,dic3,dic4],index=['One','Two','Three','Four'])
s

Exp   Field     Name     Org    Team
One    NaN     NaN   Ambika  APSSDC  Python
Two    NaN  Gaming   Pavani  APSSDC     NaN
Three    4     NaN    Surya  APSSDC   Cyber
Four   NaN     NaN  Keerthi  APSSDC    MSTP

- Retrive data in dataFrame
    - loc
        - data in that index position
    - iloc
        - Normal index value

In [60]:
s

Exp   Field     Name     Org    Team
One    NaN     NaN   Ambika  APSSDC  Python
Two    NaN  Gaming   Pavani  APSSDC     NaN
Three    4     NaN    Surya  APSSDC   Cyber
Four   NaN     NaN  Keerthi  APSSDC    MSTP

In [58]:
s.loc['One']

Exp         NaN
Field       NaN
Name     Ambika
Org      APSSDC
Team     Python
Name: One, dtype: object

In [59]:
s.iloc[0]

Exp         NaN
Field       NaN
Name     Ambika
Org      APSSDC
Team     Python
Name: One, dtype: object

In [61]:
s

Exp   Field     Name     Org    Team
One    NaN     NaN   Ambika  APSSDC  Python
Two    NaN  Gaming   Pavani  APSSDC     NaN
Three    4     NaN    Surya  APSSDC   Cyber
Four   NaN     NaN  Keerthi  APSSDC    MSTP

In [62]:
s['Column'] = 'Value'
s

Exp   Field     Name     Org    Team Column
One    NaN     NaN   Ambika  APSSDC  Python  Value
Two    NaN  Gaming   Pavani  APSSDC     NaN  Value
Three    4     NaN    Surya  APSSDC   Cyber  Value
Four   NaN     NaN  Keerthi  APSSDC    MSTP  Value

In [63]:
s.T

One     Two   Three     Four
Exp        NaN     NaN       4      NaN
Field      NaN  Gaming     NaN      NaN
Name    Ambika  Pavani   Surya  Keerthi
Org     APSSDC  APSSDC  APSSDC   APSSDC
Team    Python     NaN   Cyber     MSTP
Column   Value   Value   Value    Value

In [64]:
s

Exp   Field     Name     Org    Team Column
One    NaN     NaN   Ambika  APSSDC  Python  Value
Two    NaN  Gaming   Pavani  APSSDC     NaN  Value
Three    4     NaN    Surya  APSSDC   Cyber  Value
Four   NaN     NaN  Keerthi  APSSDC    MSTP  Value

In [65]:
s.drop('Four')

Exp   Field    Name     Org    Team Column
One    NaN     NaN  Ambika  APSSDC  Python  Value
Two    NaN  Gaming  Pavani  APSSDC     NaN  Value
Three    4     NaN   Surya  APSSDC   Cyber  Value

In [66]:
s

Exp   Field     Name     Org    Team Column
One    NaN     NaN   Ambika  APSSDC  Python  Value
Two    NaN  Gaming   Pavani  APSSDC     NaN  Value
Three    4     NaN    Surya  APSSDC   Cyber  Value
Four   NaN     NaN  Keerthi  APSSDC    MSTP  Value

In [67]:
dates = pd.date_range('2020-01-11','2020-01-22')
pd.Series(dates)

0    2020-01-11
1    2020-01-12
2    2020-01-13
3    2020-01-14
4    2020-01-15
5    2020-01-16
6    2020-01-17
7    2020-01-18
8    2020-01-19
9    2020-01-20
10   2020-01-21
11   2020-01-22
dtype: datetime64[ns]

In [68]:
dates = pd.date_range('2020-01-11',periods=7)
dates

DatetimeIndex(['2020-01-11', '2020-01-12', '2020-01-13', '2020-01-14',
               '2020-01-15', '2020-01-16', '2020-01-17'],
              dtype='datetime64[ns]', freq='D')